# Generated by Django 5.0.1 on 2024-01-29 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
